# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"interpolate_data": "Utilities.ipynb",
         "Dic2Dot": "XmlElementTree.ipynb",
         "read_asxml": "XmlElementTree.ipynb",
         "exclude_kpts": "XmlElementTree.ipynb",
         "get_ispin": "XmlElementTree.ipynb",
         "get_summary": "XmlElementTree.ipynb",
         "get_kpts": "XmlElementTree.ipynb",
         "get_tdos": "XmlElementTree.ipynb",
         "get_evals": "XmlElementTree.ipynb",
         "get_bands_pro_set": "XmlElementTree.ipynb",
         "get_dos_pro_set": "XmlElementTree.ipynb",
         "get_structure": "XmlElementTree.ipynb",
         "export_vasprun": "XmlElementTree.ipynb"}

modules = ["g_utils.py",
           "vr_parser.py"]

doc_url = "https://asaboor.github.io/pivotpy/"

git_url = "https://github.com/asaboor/pivotpy/tree/master/"

def custom_doc_links(name): return None
