# AUTOGENERATED! DO NOT EDIT! File to edit: Utilities.ipynb (unless otherwise specified).

__all__ = ['interpolate_data']

# Cell
def interpolate_data(x,y,n=10,k=3):
    """
    x: 1D array of size p
    y: ndarray of size p,q,r,....
    n: Number of points to add between two given points.
    k: Polynomial order to interpolate.

    Only axis 0 will be interpolated. If you want general interploation, use
    `from scipy.interpolate import make_interp_spline, BSpline`

    General Usage: K(p),E(p,q) input from bandstructure.
    Knew,Enew= interpolate_data(K,E,n=10,k=3) #cubic interploation
    """
    import numpy as np
    from scipy.interpolate import make_interp_spline, BSpline
    xnew=[np.linspace(x[i],x[i+1],n) for i in range(len(x)-1)]
    xnew=np.reshape(xnew,(-1))
    spl = make_interp_spline(x, y, k=k) #BSpline object
    ynew = spl(xnew)
    return xnew,ynew